[workspace]
channels = [
 "file:///data/conda",
 "https://repo.prefix.dev/meta-forge",
  "conda-forge",
]

name = "cutlass"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


[system-requirements]
cuda = "12.9"

[dependencies]
python = "3.10.*"
cuda = "12.9.*"
pytorch = { version = "*", build = "*cuda*" }
ninja = "*"
cmake = "*"
cxx-compiler = "*"
pybind11 = "*"